name: BoydWichman
favicon: null
layout_spectrum: 0.31807442218996584
typography_spectrum: 0.012030418729409575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#747476'
    - '#4b4b4b'
    - '#9b9b9d'
  brandStrength: 0.8788955812342465
  lightness: 0.40788193163461983
  saturation: 0.09159485925920308
  rhythmicContrast: 0.3582568613346666
purpose: []
